/******************************************************************************
 * Filename:       ADC_Service.h
 *
 * Description:    This file contains the ADC_Service service definitions and
 *                 prototypes.
 *
 *                 Generated by:
 *                 BDS version: 1.0.2116.0
 *                 Plugin:      Texas Instruments CC26xx BLE SDK v2.1 GATT Server plugin 1.0.5 beta
 *                 Time:        Thu Jul 14 2016 12:48:02 GMT+02:00
 *

 * Copyright (c) 2015, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef _ADC_SERVICE_H_
#define _ADC_SERVICE_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */
#include <bcomdef.h>

/*********************************************************************
 * CONSTANTS
 */
// Service UUID
#define ADC_SERVICE_SERV_UUID 0xDF95
#define ADC_SERVICE_SERV_UUID_BASE128(uuid) 0x18, 0x2F, 0x90, 0x2F, 0x84, 0x13, 0xAC, 0xBD, 0x5A, 0x41, 0x88, 0x35, LO_UINT16(uuid), HI_UINT16(uuid), 0x67, 0x87

// Value Characteristic defines
#define AS_VALUE_ID                 0
#define AS_VALUE_UUID               0x6E57
#define AS_VALUE_UUID_BASE128(uuid) 0x18, 0x2F, 0x90, 0x2F, 0x84, 0x13, 0xAC, 0xBD, 0x5A, 0x41, 0x88, 0x35, LO_UINT16(uuid), HI_UINT16(uuid), 0x67, 0x87
#define AS_VALUE_LEN                20
#define AS_VALUE_LEN_MIN            1

/*********************************************************************
 * TYPEDEFS
 */

// Fields in characteristic "Value"
//   Field "Value" format: uint8[], bits: -1

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * Profile Callbacks
 */

// Callback when a characteristic value has changed
typedef void (*AdcServiceChange_t)( uint16_t connHandle, uint16_t svcUuid, uint8_t paramID, uint8_t *pValue, uint16_t len );

typedef struct
{
  AdcServiceChange_t        pfnChangeCb;     // Called when characteristic value changes
  AdcServiceChange_t        pfnCfgChangeCb;  // Called when characteristic CCCD changes
} AdcServiceCBs_t;



/*********************************************************************
 * API FUNCTIONS
 */


/*
 * AdcService_AddService- Initializes the AdcService service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t AdcService_AddService( uint8_t rspTaskId );

/*
 * AdcService_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
extern bStatus_t AdcService_RegisterAppCBs( AdcServiceCBs_t *appCallbacks );

/*
 * AdcService_SetParameter - Set a AdcService parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t AdcService_SetParameter( uint8_t param, uint16_t len, void *value );

/*
 * AdcService_GetParameter - Get a AdcService parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t AdcService_GetParameter( uint8_t param, uint16_t *len, void *value );

/*********************************************************************
*********************************************************************/

#ifdef __cplusplus
}
#endif

#endif /* _ADC_SERVICE_H_ */

